# Generated by Django 4.2 on 2024-03-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_admin_lock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasepagelockmodel',
            options={'ordering': ('locked_at',), 'verbose_name': 'Блокировка страниц | Page Lock', 'verbose_name_plural': 'Блокировки страниц | Page Locks'},
        ),
    ]
