# Generated by Django 3.1 on 2022-02-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0003_basecomponent_frontinfo_frontinfoscreenshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecomponent',
            name='pages',
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basecomponent')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basepage')),
            ],
            options={
                'ordering': ('view_order',),
                'unique_together': {('component', 'page')},
            },
        ),
    ]
