# Generated by Django 3.1 on 2022-04-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0004_auto_20220411_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecomponent',
            unique_together={('component', 'page')},
        ),
    ]
