# Generated by Django 3.1 on 2022-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0004_auto_20220208_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomponent',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='components', through='garpix_page.PageComponent', to='garpix_page.BasePage', verbose_name='Страницы для отображения'),
        ),
    ]
