# Generated by Django 3.1 on 2022-04-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0005_auto_20220411_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecomponent',
            options={'ordering': ('view_order',), 'verbose_name': 'Компонент страницы', 'verbose_name_plural': 'Компоненты страницы'},
        ),
    ]
