# Generated by Django 3.1 on 2022-04-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0006_auto_20220412_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basecomponent', verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basepage', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='view_order',
            field=models.IntegerField(default=1, verbose_name='Порядок отображения'),
        ),
    ]
