# Generated by Django 3.1 on 2022-04-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0007_auto_20220412_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomponent',
            name='text_title_en',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
