# Generated by Django 3.1 on 2022-09-02 06:44

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0010_auto_20220829_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_field', models.CharField(max_length=255, verbose_name='Поле')),
                ('model_rule_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('rule_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('seo_title', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO заголовок страницы (title)')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO ключевые слова (keywords)')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO описание (description)')),
                ('seo_author', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO автор (author)')),
                ('seo_og_type', models.CharField(blank=True, default='website', max_length=250, verbose_name='SEO og:type')),
                ('seo_image', models.FileField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='SEO изображение')),
            ],
        ),
    ]
