# Generated by Django 3.1 on 2022-10-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0011_grapesjshtmlcomponent'),
        ('garpix_page', '0011_garpixpagesiteconfiguration'),
    ]

    operations = [
    ]
