# Generated by Django 3.1 on 2022-09-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0011_seotemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seotemplate',
            options={'verbose_name': 'Шаблон для seo', 'verbose_name_plural': 'Шаблоны для seo'},
        ),
    ]
