# Generated by Django 3.1 on 2022-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0012_auto_20220902_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotemplate',
            name='seo_author_de',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_author_en',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_author_ru',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_keywords_de',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_keywords_en',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_title_de',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO заголовок страницы (title)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO заголовок страницы (title)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_title_ru',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO заголовок страницы (title)'),
        ),
    ]
