# Generated by Django 3.1 on 2022-10-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0012_merge_20221010_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garpixpagesiteconfiguration',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
