# Generated by Django 3.1 on 2022-10-03 11:47

from django.db import migrations, models
import garpix_page.utils.all_sites


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_page', '0013_auto_20220902_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotemplate',
            name='priority_order',
            field=models.PositiveIntegerField(default=1, help_text='Чем меньше число, тем выше приоритет', verbose_name='Приоритетность применения'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='sites',
            field=models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для применения'),
        ),
    ]
