# Generated by Django 3.1 on 2022-10-03 12:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0014_auto_20221003_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seotemplate',
            options={'ordering': ['priority_order'], 'verbose_name': 'Шаблон для seo', 'verbose_name_plural': 'Шаблоны для seo'},
        ),
        migrations.AlterModelManagers(
            name='seotemplate',
            managers=[
                ('on_site', django.db.models.manager.Manager()),
            ],
        ),
    ]
