# Generated by Django 3.1 on 2022-10-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0015_auto_20221003_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
    ]
