# Generated by Django 3.1 on 2022-10-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0016_seotemplate_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seotemplate',
            options={'ordering': ['priority_order', 'id'], 'verbose_name': 'Шаблон для seo', 'verbose_name_plural': 'Шаблоны для seo'},
        ),
        migrations.AlterModelManagers(
            name='seotemplate',
            managers=[
            ],
        ),
    ]
