# Generated by Django 3.1 on 2022-10-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0017_auto_20221003_1245'),
        ('garpix_page', '0013_auto_20221010_1200'),
    ]

    operations = [
    ]
