# Generated by Django 3.1 on 2022-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0018_merge_20221010_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomponent',
            name='text_title_zh_hans',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='seo_author_zh_hans',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='seo_description_zh_hans',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='seo_keywords_zh_hans',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='seo_title_zh_hans',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO заголовок страницы (title)'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_author_zh_hans',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_description_zh_hans',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_keywords_zh_hans',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='seo_title_zh_hans',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO заголовок страницы (title)'),
        ),
    ]
