# Generated by Django 3.1 on 2022-11-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0019_auto_20221020_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Запись удалена'),
        ),
    ]
