# Generated by Django 3.1 on 2023-02-07 14:02

from django.db import migrations, models
import garpix_page.utils.all_sites


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('garpix_page', '0019_auto_20221020_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('pattern', models.CharField(help_text='Шаблон url, который будет добавлен после url страницы, к которой применяется', max_length=100, verbose_name='pattern')),
                ('model_name', models.CharField(default='', help_text='Ключ для подстановки названия модели - {model_name}', max_length=100, verbose_name='Шаблон названия модели (ключ для фронта)')),
                ('model_title', models.CharField(default='', help_text='Ключ для подстановки названия модели - {model_title}', max_length=100, verbose_name='Шаблон названия модели (для отображения)')),
                ('sort', models.PositiveIntegerField(default=1, verbose_name='Порядок отображения')),
                ('page_types', models.ManyToManyField(blank=True, related_name='subpage_urls', to='contenttypes.ContentType', verbose_name='Типы страниц для примeнения')),
                ('sites', models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения')),
            ],
            options={
                'verbose_name': 'Подстраница',
                'verbose_name_plural': 'Подстраницы',
                'ordering': ('-sort',),
            },
        ),
    ]
