# Generated by Django 3.1 on 2023-01-31 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import garpix_page.utils.all_sites


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_page', '0019_auto_20221020_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('pattern', models.CharField(max_length=100, verbose_name='pattern')),
                ('base_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hook_pages', to='garpix_page.basepage', verbose_name='Базовая страница')),
                ('sites', models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения')),
            ],
            options={
                'verbose_name': 'HookPage',
                'verbose_name_plural': 'HookPages',
            },
            managers=[
                ('on_site', django.db.models.manager.Manager()),
            ],
        ),
    ]
