# Generated by Django 3.1 on 2023-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0019_auto_20221020_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Урл страницы'),
        ),
    ]
