# Generated by Django 3.1 on 2022-11-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0020_basepage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomponent',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Запись удалена'),
        ),
    ]
