# Generated by Django 3.1 on 2023-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0020_basepage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Полный URL страницы'),
        ),
    ]
