# Generated by Django 3.1 on 2023-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0020_hookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookpage',
            name='model_name',
            field=models.CharField(default='', max_length=100, verbose_name='pattern'),
        ),
    ]
