# Generated by Django 3.1 on 2023-05-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0021_auto_20230326_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomponent',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Запись удалена'),
        ),
    ]
