# Generated by Django 4.2 on 2024-09-17 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0023_alter_basecomponent_options_alter_basepage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepage',
            options={'base_manager_name': 'objects', 'ordering': ('created_at', 'title'), 'verbose_name': 'Структура страниц | Pages structure', 'verbose_name_plural': 'Структура страниц | Pages structure'},
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='anchor_link_id',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid', message='Допустимы только латинские буквы, цифры, дефисы, знаки подчеркивания и хештеги', regex='^[a-zA-Z0-9\\-_#]*$')], verbose_name='Id для якорной ссылки'),
        ),
    ]
