# Generated by Django 4.2 on 2024-09-20 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0024_alter_basepage_options_basecomponent_anchor_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecomponent',
            name='anchor_link_id',
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='html_id',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid', message='Допустимы только латинские буквы, цифры, дефисы и знаки подчеркивания', regex='^[a-zA-Z0-9\\-_]*$')], verbose_name='HTML ID'),
        ),
    ]
