# Generated by Django 3.1 on 2021-09-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0002_auto_20210908_0926'),
        ('app', '0002_listpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница поиска',
                'verbose_name_plural': 'Страница поиска',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
    ]
