# Generated by Django 3.1 on 2022-02-08 13:04

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0003_basecomponent_frontinfo_frontinfoscreenshots'),
        ('app', '0003_searchpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
                ('image', models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basecomponent',),
        ),
        migrations.CreateModel(
            name='SliderComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basecomponent',),
        ),
        migrations.CreateModel(
            name='TextComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текст',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basecomponent',),
        ),
        migrations.CreateModel(
            name='TextDescriptionComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
                ('text', models.TextField(verbose_name='Текст')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Текст+описание',
                'verbose_name_plural': 'Текст+описание',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basecomponent',),
        ),
        migrations.CreateModel(
            name='TextImageComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Текст+изображение',
                'verbose_name_plural': 'Текст+изображение',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basecomponent',),
        ),
    ]
