# Generated by Django 3.1 on 2022-02-04 14:10

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0005_auto_20220204_1401'),
        ('app', '0003_searchpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePageComponent',
            fields=[
                ('basepagecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepagecomponent')),
                ('image', models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepagecomponent',),
        ),
        migrations.CreateModel(
            name='SliderPageComponent',
            fields=[
                ('basepagecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepagecomponent')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepagecomponent',),
        ),
        migrations.CreateModel(
            name='TextDescriptionPageComponent',
            fields=[
                ('basepagecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepagecomponent')),
                ('text', models.TextField(verbose_name='Текст')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Текст+описание',
                'verbose_name_plural': 'Текст+описание',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepagecomponent',),
        ),
        migrations.CreateModel(
            name='TextImagePageComponent',
            fields=[
                ('basepagecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepagecomponent')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Текст+изображение',
                'verbose_name_plural': 'Текст+изображение',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepagecomponent',),
        ),
        migrations.CreateModel(
            name='TextPageComponent',
            fields=[
                ('basepagecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepagecomponent')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текст',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepagecomponent',),
        ),
    ]
