# Generated by Django 3.1 on 2022-04-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0003_auto_20220411_1525'),
        ('app', '0004_textcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextDescriptionComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
                ('text', models.TextField(verbose_name='Текст')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Компонент текст+описание',
                'verbose_name_plural': 'Компоненты текст+описание',
            },
            bases=('garpix_page.basecomponent',),
        ),
    ]
