# Generated by Django 3.1 on 2022-08-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220412_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='textcomponent',
            name='text_de',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='textcomponent',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='textdescriptioncomponent',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='textdescriptioncomponent',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='textdescriptioncomponent',
            name='text_de',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='textdescriptioncomponent',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
