# Generated by Django 3.1 on 2022-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220829_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_zh_hans',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_zh_hans',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='textcomponent',
            name='text_zh_hans',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='textdescriptioncomponent',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='textdescriptioncomponent',
            name='text_zh_hans',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
